[language-server.clangd]
command = "clangd" 

[[language]]
name = "c"
scope = "source.c"
injection-regex = "c"
file-types = ["c", "h"]
shebangs = ["c"]
comment-token = "//"
language-servers = [ "clangd" ]
indent = { tab-width = 8, unit = "\t" }
auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "cpp"
scope = "source.c"
injection-regex = "cpp"
file-types = ["cpp", "hh"]
shebangs = ["cpp"]
comment-token = "//"
language-servers = [ "clangd" ]
indent = { tab-width = 8, unit = "\t" }
auto-format = true
formatter = { command = "clang-format" }

# [[language]]
# name = "python"
# # If you want to use pylsp for other features like type checking, keep this
# language-servers = ["pylsp"]

# # https://github.com/helix-editor/helix/discussions/8567#discussioncomment-7808366
# # includes a list of dependencies that need to be installed
# # python-black python-isort python-jedi python-pyflakes python-pylint python-pyls-isort python-python-lsp-black python-python-lsp-server[rope,pylint] python-rope
# [language-server.pylsp.config.pylsp]
# plugins.black.enabled = true
# plugins.pylint.enabled = true
# plugins.pyflakes.enabled = false
# plugins.pyls_mypy.enabled = true
# plugins.pyls_mypy.live_mode = false
# plugins.isort.enabled = true
# plugins.rope_autoimport.enabled = true
[[language]]
name = "python"
file-types = ["py"]
roots = ["pyproject.toml", "setup.py", ".git"]  # Project root markers
language-servers = ["pyright"]
# formatter = { command = "yapf" }
auto-format = true

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]

# [[language]]
# name = "python"
# formatter = { command = "ruff", args = ["format", "--line-length", "80", "-"] }
# auto-format = true

# [[language]]
# name = "arm"
# scope = "source.arm"
# injection-regex = "arm"
# file-types = ["s"]
# comment-tokens = "@"
# # indent = { tab-width = 4, unit = " "}
# language-servers = [ "asm-lsp" ]

# [[grammar]]
# name = "arm"
# source = { git = "https://github.com/RubixDev/tree-sitter-asm", rev = "839741fef4dab5128952334624905c82b40c7133" }

# [[language]]
# name = "arm"
# scope = "source.arm"
# file-types = ["d"]
# injection-regex = "arm"
# comment-token = "@"
# indent = { tab-width = 8, unit = "        " }
# language-servers = ["asm-lsp"]
# grammar = "arm"

# [[language]]
# name = "arm"
# scope = "source.gas"
# file-types = ["d"]
# injection-regex = "gas"
# comment-token = "@"
# indent = { tab-width = 8, unit = "        " }
# language-servers = ["asm-lsp"]
# grammar = "gas"

[[grammar]]
name = "arm"
source = { git = "https://github.com/SethBarberee/tree-sitter-asm", rev = "eee056ff31ea758eaa0ff00f0ec335f156cc5ebe" }

[[language]]
name = "arm"
scope = "source.arm"
file-types = ["s"]
injection-regex = "arm"
comment-token = "@"
indent = { tab-width = 8, unit = "        " }
language-servers = ["asm-lsp"]
grammar = "arm"

# [[grammar]]
# name = "arm"
# source = { git = "https://github.com/SethBarberee/tree-sitter-asm", rev = "eee056ff31ea758eaa0ff00f0ec335f156cc5ebe" }
